conservice/config/routes.rb
Rails.application.routes.draw do


  root 'top#login'

  get 'top/main'
  post 'users/login'
  post 'users/logout'
  post 'stores/login'
  post 'stores/logout'
  
  get 'stores/login'
  post 'stores/login'

  get 'users/login'
  post 'users/login'
  
  get 'stores/edit'
  post 'stores/edit'
  

  
  resources :stores
  resources :users
  resources :top
end

conservice/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

conservice/app/models/store.rb
class Store < ApplicationRecord
end

conservice/app/models/store_info.rb
class StoreInfo < ApplicationRecord
    belongs_to :store
end

conservice/app/models/user.rb
class User < ApplicationRecord
   
    
   
end

conservice/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

conservice/app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = Store.all
  end
  
  def new
    @stores = Store.new
  end
  
  def create
    @store = Store.new(name: params[:store][:name], pass: params[:store][:pass], tel: params[:store][:tel], period_product: params[:store][:period_product], store_product: params[:store][:store_product], pay: params[:store][:pay], card: params[:store][:card], atm: params[:store][:atm], other: params[:store][:other])
    if @store.save
      flash[:info] = 'ユーザを登録完了しました。'
      redirect_to stores_login_path
    else
      render new_store_path
    end
  end  
  
  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end
  
  def login
    unless params[:name] && params[:pass]
      render 'login'
    else
      if Store.find_by(name: params[:name], pass: params[:pass])
        session[:login_store] = params[:name]
        pp "T"
        redirect_to stores_path
      else 
        flash[:warning] = '名前、もしくはパスワードが間違っています。'
        pp "F"
        render 'login'
      end
    end
  end
  
  def show
    @store = Store.find(params[:id])
  end
  
  def edit
    @store = Store.find(params[:id])
  end

  def update
    @store = Store.find(params[:id])
    @store.update(name: params[:store][:name],tel: params[:store][:tel], 期間限定の商品: params[:store][:period_product], 当店限定の商品: params[:store][:store_product], pay: params[:store][:pay], card: params[:store][:card], atm: params[:store][:atm], その他: params[:store][:other])
    redirect_to '/'
  end
  
end

conservice/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
      if session[:login_uid]
         render 'main'
      else
         render 'login'
      end
  end
end

conservice/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @stores = Store.all
    @users = User.all
  end
  
  def new
    @users = User.new
    @stores = Store.new
  end
  
  def create
    @user = User.new(name: params[:user][:name], pass: params[:user][:pass])
    if @user.save
      flash[:info] = '登録しました。'
      redirect_to users_login_path 
    else
      render new_user_path
    end
  end
  
  def destroy
    reset_session
    redirect_to root_path
  end
  
  def login
      @user = User.find_by(name: params[:name],pass: params[:pass])
     if @user
       session[:login_uid] = @user.id
       flash[:info] = 'ログインしています。'
       redirect_to users_path 
     else
        flash[:miss] = 'もう一度入力してください。'
      render users_login_path
      
     end
  end    

  def show
   session.delete(:login_uid)
   flash[:info] = 'ログアウトしました。'
   redirect_to users_login_path 
  end
end

conservice/app/helpers/application_helper.rb
module ApplicationHelper
end

conservice/app/helpers/stores_helper.rb
module StoresHelper
end

conservice/app/helpers/top_helper.rb
module TopHelper
end

conservice/app/helpers/users_helper.rb
module UsersHelper
end

conservice/app/views/customers/top.html.erb
<h1>Tajiri'sコンビニサービス検索サイト</h1>

<%= link_to "ログインする" , login_path %>
<%= link_to "新規登録する" , new_user_path %>

<%= @user %>

conservice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Conservice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<% if flash[:info] %>
 <%= flash[:info] %>
 <% end %>
 


  <body>
    <%= yield %>
  </body>
</html>

conservice/app/views/stores/edit.html.erb
<h1>コンビニサービス検索サイト</h1>

<% if flash[:success] %>
<%= flash[:success] %>
<% end %>
  
<% if flash[:danger] %>
<%= flash[:danger] %>
<% end %>

<%= form_for @stores, url: {action: :update} do |f| %>
<p>
  <%= f.label :name, '店舗名:' %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :pass, 'パスワード:' %>
  <%= f.text_field :pass %>
  <br>
  <%= f.label :tel, 'TEL(ハイフン無し):' %>
  <%= f.text_field :tel %>
  <br>
  <%= f.label :period_product, '期間限定の商品:' %>
  <%= f.text_field :period_product %>
  <br>
  <%= f.label :store_product, '当店限定の商品:' %>
  <%= f.text_field :store_product %>
  <br>
  <%= f.label :pay, 'お支払い方法(クレジット、スマホ決済等):' %>
  <%= f.text_field :pay %>
  <br>
  <%= f.label :card, 'ご利用可能なカード:' %>
  <%= f.text_field :card %>
  <br>
  <%= f.label :atm, 'ATM:' %>
  <%= f.text_field :atm %>
  <br>
  <%= f.label :other, 'おしらせ:' %>
  <%= f.text_field :other %>
</p>
<p>
  <%= f.submit '登録' %>
</p>
<% end %>

<p><%= link_to '戻る', stores_path %></p>

conservice/app/views/stores/index.html.erb
<h1><button><%= link_to 'ログアウト', stores_login_path %></button>コンビニサービス検索サイト</h1>
<% @store = Store.new unless @post %>
<% @stores.each do |store| %>
<p><h2><%= store.name %>様トップページ</h2>
<button><%= link_to '登録内容を編集' , stores_edit_path %></button>
</p>
<hr>
<strong>
    <p>TEL：<td><%= store.tel %></td></p>
    <p>期間限定の商品：<td><%= store.period_product %></td></p>
    <p>当店限定の商品：<td><%= store.store_product %></td></p>
    <p>お会計方法：<td><%= store.pay %></td></p>
    <p>ご利用できるカード：<td><%= store.card %></td></p>
    <p>ATM：<td><%= store.atm %></td></p>
    <p>その他おしらせ：<td><%= store.other %></td></p>
</strong>
<% end %>

conservice/app/views/stores/login.html.erb
<h1>コンビニサービス検索サイト</h1>
<% @store = Store.new unless @post %>

<h2>企業様ログインページ</h2>
  
  <% if flash[:info] %>
    <%= flash[:info] %>
  <% end %>
  
  <% if flash[:warning] %>
    <% pp flash %>
    <%= flash[:warning] %>
  <% end %>
  
<%= form_tag '/stores/login',method: :post do %>
  <%= label_tag :name, '企業・店舗名' %>
  <%= text_field_tag :name %>
  <%= label_tag :pass, 'パスワード' %>
  <%= password_field_tag :pass %>
  <%= submit_tag 'サインイン' %>
<% end %>

<br>
<%= link_to '企業・店舗新規登録はこちらへ', new_store_path %>
<button><%= link_to '戻る', root_path %></button>

conservice/app/views/stores/new.html.erb
<h1>新規登録（企業様画面）</h1>
<%= form_for @stores, url: {action: :create} do |f| %>
<p>
  <%= f.label :name, '店舗名:' %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :pass, 'パスワード:' %>
  <%= f.text_field :pass %>
  <br>
  <%= f.label :tel, 'TEL(ハイフン無し):' %>
  <%= f.text_field :tel %>
  <br>
  <%= f.label :period_product, '期間限定の商品:' %>
  <%= f.text_field :period_product %>
  <br>
  <%= f.label :store_product, '当店限定の商品:' %>
  <%= f.text_field :store_product %>
  <br>
  <%= f.label :pay, 'お支払い方法(クレジット、スマホ決済等):' %>
  <%= f.text_field :pay %>
  <br>
  <%= f.label :card, 'ご利用可能なカード:' %>
  <%= f.text_field :card %>
  <br>
  <%= f.label :atm, 'ATM:' %>
  <%= f.text_field :atm %>
  <br>
  <%= f.label :other, 'おしらせ:' %>
  <%= f.text_field :other %>
</p>
<p>
  <%= f.submit '登録' %>
</p>
<% end %>
<p><%= link_to '戻る', :back %></p>

conservice/app/views/top/login.html.erb
<h1>ログイン画面</h1>
<p>扱う方を選択してページへ移行してください。</p>


<%= link_to '顧客様はこちら', users_login_path %><br>
<%= link_to '店舗様はこちら', stores_login_path %>

conservice/app/views/users/index.html.erb
<h1>コンビニサービス検索サイト</h1>



<h3>店舗検索</h3>
<%= form_tag stores_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search %>
    <%= submit_tag "検索", :name => nil %>
  </p>
<% end %>

<% @stores.each do |e| %>
<%= link_to e.name, stores_path(e) %>
<% end %>


<%= link_to 'ログアウト' , users_logout_path %>

conservice/app/views/users/login.html.erb
<h1>コンビニサービス検索サイト</h1>

<p><% flash[:miss] %></p>


<%= form_for @users, url: {action: :create} do |t| %>
<p>
  <%= t.label :name, '名前:' %>
  <%= t.text_field :name %>
  <br>
  <%= t.label :pass, 'パスワード:' %>
  <%= t.text_field :pass %>
<% end %>

<p><%= link_to '戻る', root_path %></p>
<%= link_to '客側新規登録', new_user_path %>

conservice/app/views/users/new.html.erb
<h1>新規登録（お客様）</h1>

<%= form_for @users, url: {action: :create} do |f| %>
<p>
  <%= f.label :name, '名前:' %>
  <%= f.text_field :name %>
  
    <%= f.label :pass, 'パスワード:' %>
    <%= f.password_field :pass %>
</p>
<p>
  <%= f.submit '登録' %>
</p>
<% end %>
  <p><%= link_to '戻る', root_path %></p>